title: "Documentação Etica.Dev"
description: "Documentação de Criação de Nuvem, Gerência de Time e Pessoa Desenvolvedora do Etica.Dev. Licença de uso livre"
image:
  path: '/img/aguia-pescadora-banner.jpg'
  height: 640
  width: 1280

defaults:
  - scope:
      path: ""
    values:
      image: 
        path: '/img/aguia-pescadora-banner.jpg'
        height: 640
        width: 1280

# see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
lang: 'pt'

twitter:
  username: EticaAI
  card: summary

plugins:
  - jekyll-seo-tag